# Generated by Django 4.2.7 on 2023-12-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0002_alter_category_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
    ]
