# Generated by Django 4.2.7 on 2023-12-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_productgallery"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productgallery",
            options={
                "verbose_name": "productgallery",
                "verbose_name_plural": "product gallery",
            },
        ),
        migrations.RemoveField(model_name="product", name="stock",),
        migrations.AddField(
            model_name="variation", name="stock", field=models.IntegerField(null=True),
        ),
    ]
