# Generated by Django 4.2.7 on 2023-12-11 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_alter_productgallery_options_remove_product_stock_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color_name", models.CharField(max_length=50)),
                ("color_code", models.CharField(max_length=15)),
                ("is_available", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size_range", models.CharField(max_length=60)),
                ("is_available", models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name="variation", old_name="is_active", new_name="is_available",
        ),
        migrations.RenameField(
            model_name="variation", old_name="stock", new_name="quantity",
        ),
        migrations.RemoveField(model_name="variation", name="variation_category",),
        migrations.RemoveField(model_name="variation", name="variation_value",),
        migrations.CreateModel(
            name="VariantImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="No image available", upload_to="photos/variants"
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.variation",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="variation",
            name="color",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="store.color"
            ),
        ),
        migrations.AddField(
            model_name="variation",
            name="size",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="store.size"
            ),
        ),
    ]
