# Generated by Django 4.2.7 on 2023-12-12 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_color_size_rename_is_active_variation_is_available_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product", old_name="price", new_name="product_price",
        ),
    ]
