# Generated by Django 4.2.7 on 2023-11-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_account_groups_account_is_superuser_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="phone_number",
            field=models.CharField(max_length=50),
        ),
    ]
