# Generated by Django 4.2.5 on 2023-11-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_account_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="block_user",
            field=models.BooleanField(default=False),
        ),
    ]
