# Generated by Django 4.2.5 on 2023-11-22 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_account_block_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account", old_name="block_user", new_name="is_blocked",
        ),
    ]
